### ISSUE TITLE
Compiled version?

### ISSUE THREAD

**Issue by tomasdev** [mathiasbynens/hashtag-regex#1]
Hi there, Unicode fans! Is there a reason not to compile the regex once and use it? I'm looking specifically at the lines that check for the unicode dependency versions / why is this its own module instead of a gist?

**Comment by mathiasbynens** [comment]
I agree that compiling the regex at run-time would be a terrible idea :)

This repo contains the scripts that compile the regex. The compiled version is not part of the repo but it is what you’ll be using when doing `require('hashtag-regex')`. https://github.com/mathiasbynens/hashtag-regex/blob/ddc3243d0b2132a33279968e89299e630e630625/package.json#L34
